[project]
name= "src"
version="0.0.1"
description="first mlops project"
authors = [{name = "anshu"}]

[tools.setuptools]
packages={find={}}

[tool.setuptools.dynamic]
dependencies={file="requirements.txt"}
